package org.andot.share.api.entity;

import lombok.Data;
import lombok.ToString;

import java.io.Serializable;
import java.util.Date;

@Data
@ToString
public class Action implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.action_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Integer actionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.action_name
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private String actionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.action_type
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Byte actionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.action_url
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private String actionUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.menu_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.caption
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private String caption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.disabled
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Byte disabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.create_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.update_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.delete_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Date deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table action
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private static final long serialVersionUID = 1L;

}