package org.andot.share.api.entity;

import java.io.Serializable;

public class MenuOperatePower implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_operate_power.menu_power_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Integer menuPowerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_operate_power.power_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Integer powerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_operate_power.menu_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_operate_power.menu_power_id
     *
     * @return the value of menu_operate_power.menu_power_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Integer getMenuPowerId() {
        return menuPowerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_operate_power.menu_power_id
     *
     * @param menuPowerId the value for menu_operate_power.menu_power_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setMenuPowerId(Integer menuPowerId) {
        this.menuPowerId = menuPowerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_operate_power.power_id
     *
     * @return the value of menu_operate_power.power_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Integer getPowerId() {
        return powerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_operate_power.power_id
     *
     * @param powerId the value for menu_operate_power.power_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setPowerId(Integer powerId) {
        this.powerId = powerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_operate_power.menu_id
     *
     * @return the value of menu_operate_power.menu_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_operate_power.menu_id
     *
     * @param menuId the value for menu_operate_power.menu_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", menuPowerId=").append(menuPowerId);
        sb.append(", powerId=").append(powerId);
        sb.append(", menuId=").append(menuId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MenuOperatePower other = (MenuOperatePower) that;
        return (this.getMenuPowerId() == null ? other.getMenuPowerId() == null : this.getMenuPowerId().equals(other.getMenuPowerId()))
            && (this.getPowerId() == null ? other.getPowerId() == null : this.getPowerId().equals(other.getPowerId()))
            && (this.getMenuId() == null ? other.getMenuId() == null : this.getMenuId().equals(other.getMenuId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMenuPowerId() == null) ? 0 : getMenuPowerId().hashCode());
        result = prime * result + ((getPowerId() == null) ? 0 : getPowerId().hashCode());
        result = prime * result + ((getMenuId() == null) ? 0 : getMenuId().hashCode());
        return result;
    }
}