package org.andot.share.api.entity;

import java.io.Serializable;

public class MenuElement implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_element.menu_element_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Integer menuElementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_element.menu_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_element.element_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Integer elementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_element.menu_element_id
     *
     * @return the value of menu_element.menu_element_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Integer getMenuElementId() {
        return menuElementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_element.menu_element_id
     *
     * @param menuElementId the value for menu_element.menu_element_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setMenuElementId(Integer menuElementId) {
        this.menuElementId = menuElementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_element.menu_id
     *
     * @return the value of menu_element.menu_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_element.menu_id
     *
     * @param menuId the value for menu_element.menu_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_element.element_id
     *
     * @return the value of menu_element.element_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Integer getElementId() {
        return elementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_element.element_id
     *
     * @param elementId the value for menu_element.element_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setElementId(Integer elementId) {
        this.elementId = elementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", menuElementId=").append(menuElementId);
        sb.append(", menuId=").append(menuId);
        sb.append(", elementId=").append(elementId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MenuElement other = (MenuElement) that;
        return (this.getMenuElementId() == null ? other.getMenuElementId() == null : this.getMenuElementId().equals(other.getMenuElementId()))
            && (this.getMenuId() == null ? other.getMenuId() == null : this.getMenuId().equals(other.getMenuId()))
            && (this.getElementId() == null ? other.getElementId() == null : this.getElementId().equals(other.getElementId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMenuElementId() == null) ? 0 : getMenuElementId().hashCode());
        result = prime * result + ((getMenuId() == null) ? 0 : getMenuId().hashCode());
        result = prime * result + ((getElementId() == null) ? 0 : getElementId().hashCode());
        return result;
    }
}