package org.andot.share.api.entity;

import java.io.Serializable;

public class OrganUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organ_user.organ_user_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Integer organUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organ_user.user_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organ_user.organ_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Integer organId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table organ_user
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organ_user.organ_user_id
     *
     * @return the value of organ_user.organ_user_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Integer getOrganUserId() {
        return organUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organ_user.organ_user_id
     *
     * @param organUserId the value for organ_user.organ_user_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setOrganUserId(Integer organUserId) {
        this.organUserId = organUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organ_user.user_id
     *
     * @return the value of organ_user.user_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organ_user.user_id
     *
     * @param userId the value for organ_user.user_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organ_user.organ_id
     *
     * @return the value of organ_user.organ_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Integer getOrganId() {
        return organId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organ_user.organ_id
     *
     * @param organId the value for organ_user.organ_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setOrganId(Integer organId) {
        this.organId = organId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ_user
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", organUserId=").append(organUserId);
        sb.append(", userId=").append(userId);
        sb.append(", organId=").append(organId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ_user
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OrganUser other = (OrganUser) that;
        return (this.getOrganUserId() == null ? other.getOrganUserId() == null : this.getOrganUserId().equals(other.getOrganUserId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getOrganId() == null ? other.getOrganId() == null : this.getOrganId().equals(other.getOrganId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ_user
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrganUserId() == null) ? 0 : getOrganUserId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getOrganId() == null) ? 0 : getOrganId().hashCode());
        return result;
    }
}