package org.andot.share.api.entity;

import java.io.Serializable;

public class ResourcesGroups implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources_groups.res_group_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Integer resGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources_groups.resources_type
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Byte resourcesType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources_groups.resources_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private byte[] resourcesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources_groups.groups_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private byte[] groupsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources_groups.res_group_id
     *
     * @return the value of resources_groups.res_group_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Integer getResGroupId() {
        return resGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources_groups.res_group_id
     *
     * @param resGroupId the value for resources_groups.res_group_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setResGroupId(Integer resGroupId) {
        this.resGroupId = resGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources_groups.resources_type
     *
     * @return the value of resources_groups.resources_type
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Byte getResourcesType() {
        return resourcesType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources_groups.resources_type
     *
     * @param resourcesType the value for resources_groups.resources_type
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setResourcesType(Byte resourcesType) {
        this.resourcesType = resourcesType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources_groups.resources_id
     *
     * @return the value of resources_groups.resources_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public byte[] getResourcesId() {
        return resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources_groups.resources_id
     *
     * @param resourcesId the value for resources_groups.resources_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setResourcesId(byte[] resourcesId) {
        this.resourcesId = resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources_groups.groups_id
     *
     * @return the value of resources_groups.groups_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public byte[] getGroupsId() {
        return groupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources_groups.groups_id
     *
     * @param groupsId the value for resources_groups.groups_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setGroupsId(byte[] groupsId) {
        this.groupsId = groupsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", resGroupId=").append(resGroupId);
        sb.append(", resourcesType=").append(resourcesType);
        sb.append(", resourcesId=").append(resourcesId);
        sb.append(", groupsId=").append(groupsId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ResourcesGroups other = (ResourcesGroups) that;
        return (this.getResGroupId() == null ? other.getResGroupId() == null : this.getResGroupId().equals(other.getResGroupId()))
            && (this.getResourcesType() == null ? other.getResourcesType() == null : this.getResourcesType().equals(other.getResourcesType()))
            && (this.getResourcesId() == null ? other.getResourcesId() == null : this.getResourcesId().equals(other.getResourcesId()))
            && (this.getGroupsId() == null ? other.getGroupsId() == null : this.getGroupsId().equals(other.getGroupsId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getResGroupId() == null) ? 0 : getResGroupId().hashCode());
        result = prime * result + ((getResourcesType() == null) ? 0 : getResourcesType().hashCode());
        result = prime * result + ((getResourcesId() == null) ? 0 : getResourcesId().hashCode());
        result = prime * result + ((getGroupsId() == null) ? 0 : getGroupsId().hashCode());
        return result;
    }
}