package org.andot.share.api.entity;

import java.io.Serializable;
import java.util.Date;

public class Organ implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organ.organ_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Integer organId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organ.organ_name
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private String organName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organ.organ_type
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Byte organType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organ.order_code
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Byte orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organ.organ_parent_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Integer organParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organ.caption
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private String caption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organ.disabled
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Byte disabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organ.create_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organ.update_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organ.delete_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Date deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table organ
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organ.organ_id
     *
     * @return the value of organ.organ_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Integer getOrganId() {
        return organId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organ.organ_id
     *
     * @param organId the value for organ.organ_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setOrganId(Integer organId) {
        this.organId = organId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organ.organ_name
     *
     * @return the value of organ.organ_name
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public String getOrganName() {
        return organName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organ.organ_name
     *
     * @param organName the value for organ.organ_name
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setOrganName(String organName) {
        this.organName = organName == null ? null : organName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organ.organ_type
     *
     * @return the value of organ.organ_type
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Byte getOrganType() {
        return organType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organ.organ_type
     *
     * @param organType the value for organ.organ_type
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setOrganType(Byte organType) {
        this.organType = organType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organ.order_code
     *
     * @return the value of organ.order_code
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Byte getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organ.order_code
     *
     * @param orderCode the value for organ.order_code
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setOrderCode(Byte orderCode) {
        this.orderCode = orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organ.organ_parent_id
     *
     * @return the value of organ.organ_parent_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Integer getOrganParentId() {
        return organParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organ.organ_parent_id
     *
     * @param organParentId the value for organ.organ_parent_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setOrganParentId(Integer organParentId) {
        this.organParentId = organParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organ.caption
     *
     * @return the value of organ.caption
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public String getCaption() {
        return caption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organ.caption
     *
     * @param caption the value for organ.caption
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setCaption(String caption) {
        this.caption = caption == null ? null : caption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organ.disabled
     *
     * @return the value of organ.disabled
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Byte getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organ.disabled
     *
     * @param disabled the value for organ.disabled
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setDisabled(Byte disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organ.create_time
     *
     * @return the value of organ.create_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organ.create_time
     *
     * @param createTime the value for organ.create_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organ.update_time
     *
     * @return the value of organ.update_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organ.update_time
     *
     * @param updateTime the value for organ.update_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organ.delete_time
     *
     * @return the value of organ.delete_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organ.delete_time
     *
     * @param deleteTime the value for organ.delete_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", organId=").append(organId);
        sb.append(", organName=").append(organName);
        sb.append(", organType=").append(organType);
        sb.append(", orderCode=").append(orderCode);
        sb.append(", organParentId=").append(organParentId);
        sb.append(", caption=").append(caption);
        sb.append(", disabled=").append(disabled);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleteTime=").append(deleteTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Organ other = (Organ) that;
        return (this.getOrganId() == null ? other.getOrganId() == null : this.getOrganId().equals(other.getOrganId()))
            && (this.getOrganName() == null ? other.getOrganName() == null : this.getOrganName().equals(other.getOrganName()))
            && (this.getOrganType() == null ? other.getOrganType() == null : this.getOrganType().equals(other.getOrganType()))
            && (this.getOrderCode() == null ? other.getOrderCode() == null : this.getOrderCode().equals(other.getOrderCode()))
            && (this.getOrganParentId() == null ? other.getOrganParentId() == null : this.getOrganParentId().equals(other.getOrganParentId()))
            && (this.getCaption() == null ? other.getCaption() == null : this.getCaption().equals(other.getCaption()))
            && (this.getDisabled() == null ? other.getDisabled() == null : this.getDisabled().equals(other.getDisabled()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleteTime() == null ? other.getDeleteTime() == null : this.getDeleteTime().equals(other.getDeleteTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrganId() == null) ? 0 : getOrganId().hashCode());
        result = prime * result + ((getOrganName() == null) ? 0 : getOrganName().hashCode());
        result = prime * result + ((getOrganType() == null) ? 0 : getOrganType().hashCode());
        result = prime * result + ((getOrderCode() == null) ? 0 : getOrderCode().hashCode());
        result = prime * result + ((getOrganParentId() == null) ? 0 : getOrganParentId().hashCode());
        result = prime * result + ((getCaption() == null) ? 0 : getCaption().hashCode());
        result = prime * result + ((getDisabled() == null) ? 0 : getDisabled().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleteTime() == null) ? 0 : getDeleteTime().hashCode());
        return result;
    }
}