package org.andot.share.api.entity;

import java.io.Serializable;
import java.util.Date;

public class PageElement implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_element.page_element_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Integer pageElementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_element.page_element_name
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private String pageElementName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_element.page_element_code
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private String pageElementCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_element.page_element_type
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Byte pageElementType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_element.page_element_url
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private String pageElementUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_element.disabled
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private String disabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_element.create_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_element.update_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_element.delete_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Date deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table page_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_element.page_element_id
     *
     * @return the value of page_element.page_element_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Integer getPageElementId() {
        return pageElementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_element.page_element_id
     *
     * @param pageElementId the value for page_element.page_element_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setPageElementId(Integer pageElementId) {
        this.pageElementId = pageElementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_element.page_element_name
     *
     * @return the value of page_element.page_element_name
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public String getPageElementName() {
        return pageElementName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_element.page_element_name
     *
     * @param pageElementName the value for page_element.page_element_name
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setPageElementName(String pageElementName) {
        this.pageElementName = pageElementName == null ? null : pageElementName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_element.page_element_code
     *
     * @return the value of page_element.page_element_code
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public String getPageElementCode() {
        return pageElementCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_element.page_element_code
     *
     * @param pageElementCode the value for page_element.page_element_code
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setPageElementCode(String pageElementCode) {
        this.pageElementCode = pageElementCode == null ? null : pageElementCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_element.page_element_type
     *
     * @return the value of page_element.page_element_type
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Byte getPageElementType() {
        return pageElementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_element.page_element_type
     *
     * @param pageElementType the value for page_element.page_element_type
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setPageElementType(Byte pageElementType) {
        this.pageElementType = pageElementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_element.page_element_url
     *
     * @return the value of page_element.page_element_url
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public String getPageElementUrl() {
        return pageElementUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_element.page_element_url
     *
     * @param pageElementUrl the value for page_element.page_element_url
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setPageElementUrl(String pageElementUrl) {
        this.pageElementUrl = pageElementUrl == null ? null : pageElementUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_element.disabled
     *
     * @return the value of page_element.disabled
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public String getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_element.disabled
     *
     * @param disabled the value for page_element.disabled
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setDisabled(String disabled) {
        this.disabled = disabled == null ? null : disabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_element.create_time
     *
     * @return the value of page_element.create_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_element.create_time
     *
     * @param createTime the value for page_element.create_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_element.update_time
     *
     * @return the value of page_element.update_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_element.update_time
     *
     * @param updateTime the value for page_element.update_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_element.delete_time
     *
     * @return the value of page_element.delete_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_element.delete_time
     *
     * @param deleteTime the value for page_element.delete_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pageElementId=").append(pageElementId);
        sb.append(", pageElementName=").append(pageElementName);
        sb.append(", pageElementCode=").append(pageElementCode);
        sb.append(", pageElementType=").append(pageElementType);
        sb.append(", pageElementUrl=").append(pageElementUrl);
        sb.append(", disabled=").append(disabled);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleteTime=").append(deleteTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PageElement other = (PageElement) that;
        return (this.getPageElementId() == null ? other.getPageElementId() == null : this.getPageElementId().equals(other.getPageElementId()))
            && (this.getPageElementName() == null ? other.getPageElementName() == null : this.getPageElementName().equals(other.getPageElementName()))
            && (this.getPageElementCode() == null ? other.getPageElementCode() == null : this.getPageElementCode().equals(other.getPageElementCode()))
            && (this.getPageElementType() == null ? other.getPageElementType() == null : this.getPageElementType().equals(other.getPageElementType()))
            && (this.getPageElementUrl() == null ? other.getPageElementUrl() == null : this.getPageElementUrl().equals(other.getPageElementUrl()))
            && (this.getDisabled() == null ? other.getDisabled() == null : this.getDisabled().equals(other.getDisabled()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleteTime() == null ? other.getDeleteTime() == null : this.getDeleteTime().equals(other.getDeleteTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPageElementId() == null) ? 0 : getPageElementId().hashCode());
        result = prime * result + ((getPageElementName() == null) ? 0 : getPageElementName().hashCode());
        result = prime * result + ((getPageElementCode() == null) ? 0 : getPageElementCode().hashCode());
        result = prime * result + ((getPageElementType() == null) ? 0 : getPageElementType().hashCode());
        result = prime * result + ((getPageElementUrl() == null) ? 0 : getPageElementUrl().hashCode());
        result = prime * result + ((getDisabled() == null) ? 0 : getDisabled().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleteTime() == null) ? 0 : getDeleteTime().hashCode());
        return result;
    }
}